# The entrypoint (dist/run.sh) is generated by the build on purpose: viam's
# cloud reload treats a module whose entrypoint already exists in the repo as
# "pre-built" and skips packaging entirely.
module.tar.gz: run.sh first_run.sh pyproject.toml uv.lock meta.json $(shell find src -name '*.py')
	tar czf $@ --exclude='__pycache__' --exclude='*.pyc' $^

test:
	python3 -m pytest tests/

clean:
	rm -rf module.tar.gz dist

.PHONY: setup test clean
