module.tar.gz: run.sh first_run.sh pyproject.toml uv.lock meta.json $(shell find src -name '*.py')
	tar czf $@ --exclude='__pycache__' --exclude='*.pyc' $^

# The entrypoint (run.sh) is generated by the build on purpose: viam's
# cloud reload treats a module whose entrypoint already exists in the repo as
# "pre-built" and skips packaging entirely.
run.sh: run.nodetect.sh
	cp run.nodetect.sh run.sh

test:
	python3 -m pytest tests/

clean:
	rm -rf module.tar.gz run.sh

.PHONY: test clean
